---
AWSTemplateFormatVersion: 2010-09-09
Description: "This CFN Template creates a Hugo Build for Static Site devopsams.com."
Parameters:
  ManagedResourcePrefix:
    Type: 'String'
    Default: HUGO
    Description: 'Prefix for the managed resources'
  DefaultVPC:
    Type: 'String'
    Default: vpc-0a58795060b0ac716
    Description: 'Defaut VPC ID'
  DefaultSUBNET:
    Type: 'String'
    Default: subnet-081b92a3cfb26b3e7
    Description: 'Defaut Subnet ID'
Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ManagedResourcePrefix}-CodeBuild-Role
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: !Sub ${ManagedResourcePrefix}-CodeBuild-Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:*'
                - 'ec2:CreateNetworkInterface'
                - 'ec2:DescribeNetworkInterfaces'
                - 'ec2:DeleteNetworkInterface'
                - 'ec2:DescribeSubnets'
                - 'ec2:DescribeSecurityGroups'
                - 'ec2:DescribeDhcpOptions'
                - 'ec2:DescribeVpcs'
                - 'ec2:CreateNetworkInterfacePermission'
                - 'secretsmanager:GetSecretValue' 
                - 'codeconnections:UseConnection'
                Effect: Allow
                Resource: '*'
  CodeBuildSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${ManagedResourcePrefix}-Codebuild-SG  # Optional, can be removed to auto-generate
      GroupDescription: 'CodeBuild SecurityGroup'
      VpcId: !Ref DefaultVPC
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 172.31.0.0/16  # Internal VPC CIDR block
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
  # CodeBuildProject:
  #   Type: AWS::CodeBuild::Project
  #   Properties:
  #     Name: !Sub ${ManagedResourcePrefix}-CodeBuild-Project
  #     ServiceRole: !GetAtt CodeBuildRole.Arn
  #     Artifacts:
  #       Type: NO_ARTIFACTS
  #     Environment:
  #       Type: LINUX_CONTAINER
  #       ComputeType: BUILD_GENERAL1_SMALL
  #       Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
  #       ImagePullCredentialsType: CODEBUILD
  #       EnvironmentVariables:
  #         - Name: BucketName
  #           Value: devopsams.com
  #     Source:
  #       Type: GITHUB
  #       Location: https://github.com/azamsajjad/devopsams.git
  #       Auth:
  #         Type: OAUTH
  #         Resource: !Sub "{{resolve:secretsmanager:GitHubToken::token}}"
  #       Webhook: true
  #       ConnectionArn: arn:aws:codeconnections:us-east-1:767665886117:connection/7fb03b80-b293-475d-a404-9630451fe269
  #       BuildSpec: buildspec.yaml
  #     TimeoutInMinutes: 10
  #     VpcConfig:
  #       VpcId: !Ref DefaultVPC
  #       Subnets: 
  #         - !Ref DefaultSUBNET  
  #       SecurityGroupIds: 
  #         - !Ref CodeBuildSecurityGroup
  #     Cache:
  #       Type: S3
  #       Location: devopsams.com/codebuild
  #     LogsConfig:  # Corrected the case
  #       CloudWatchLogs:
  #         Status: ENABLED
  #         GroupName: codebuild/Hugo
  #     Triggers:
  #       Webhook: true
  #       FilterGroups:
  #         - - Type: EVENT
  #             Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED
  #           - Type: BASE_REF
  #             Pattern: ^refs/heads/main$
  #             ExcludeMatchedPattern: false
  #         - - Type: EVENT
  #             Pattern: PUSH
  #           - Type: HEAD_REF
  #             Pattern: ^refs/heads/.*
  #           - Type: FILE_PATH
  #             Pattern: README.MD
  #             ExcludeMatchedPattern: true